import Footer from "@/components/layout/footer";
import Main from "@/components/layout/main";
import Navigation from "@/components/navigation/navigation";
import AppControls from "@/controls/appControls";
import { routing } from "@/i18n/routing";
import type { Metadata } from "next";
import { hasLocale } from "next-intl";
import { setRequestLocale } from "next-intl/server";
import { notFound } from "next/dist/client/components/navigation";
import { Inter, Outfit } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const outfit = Outfit({ subsets: ["latin"], variable: "--font-outfit" });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export function generateStaticParams() {
    return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
    children,
    params,
}: Readonly<{
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}>) {
    const { locale } = await params;
    if (!hasLocale(routing.locales, locale)) {
        notFound();
    }
    // Enable static renderin   g
    setRequestLocale(locale);

    return (
        <html lang={locale}>
            <body className={`${inter.variable} ${outfit.variable} antialiased`}>
                <AppControls>
                    <Navigation />
                    <Main>{children}</Main>
                    <Footer Logo={<div />} />
                </AppControls>
            </body>
        </html>
    );
}
