import Footer from "@/components/layout/footer";
import Main from "@/components/layout/main";
import Navigation from "@/components/navigation/navigation";
import Logo from "@/components/ui/logo";
import ScrollToHashOnLoad from "@/components/ui/ScrollToHashOnLoad";
import AppControls from "@/controls/appControls";
import { routing } from "@/i18n/routing";
import type { Metadata } from "next";
import { hasLocale } from "next-intl";
import { setRequestLocale } from "next-intl/server";
import { notFound } from "next/dist/client/components/navigation";
import { Inter, Outfit, Silkscreen } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const outfit = Outfit({ subsets: ["latin"], variable: "--font-outfit" });
const silkscreen = Silkscreen({
    subsets: ["latin"],
    weight: "400",
    variable: "--font-silkscreen",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export function generateStaticParams() {
    return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
    children,
    params,
}: Readonly<{
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}>) {
    const { locale } = await params;
    if (!hasLocale(routing.locales, locale)) {
        notFound();
    }
    // Enable static rendering
    setRequestLocale(locale);

    return (
        <html lang={locale}>
            <body
                className={`${inter.variable} ${outfit.variable} ${silkscreen.variable} antialiased`}
            >
                <AppControls>
                    <Navigation />
                    <ScrollToHashOnLoad />
                    <Main>{children}</Main>
                    <Footer Logo={<Logo />} />
                </AppControls>
            </body>
        </html>
    );
}
